<a href="https://colab.research.google.com/github/DepartmentOfStatisticsPUE/air-2020/blob/master/notebooks/5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

$$
A = 
\begin{pmatrix}
1& 2& -1& 0 \\ 
3 &-2& 4& 5\\ 
2 &6& 5 &-3\\ 
0 &1& 5 &-4\\ 
\end{pmatrix}
$$ ,

$$
B = 
\begin{pmatrix}
3 & 6 \\
4 & 0 \\
2 & -1 \\
1 & 1 \\
\end{pmatrix}
$$

In [0]:
A = np.array( [ (1, 2, -1, 0), 
                (3, -2, 4, 5), 
                (2, 6, 5, -3), 
                (0, 1, 5, -4)] )

B = np.array( [(3, 6), (4, 0), (2, -1), (1, 1)] )

In [0]:
print(A)
print(B)

[[ 1  2 -1  0]
 [ 3 -2  4  5]
 [ 2  6  5 -3]
 [ 0  1  5 -4]]
[[ 3  6]
 [ 4  0]
 [ 2 -1]
 [ 1  1]]


Zadanie 1. oblicz wyznacznik macierzy **A**.


In [0]:
np.linalg.det(A)

154.00000000000006

Zadanie 2. znajdź iloczyn macierzy **AB**

In [0]:
A @ B ## wyłącznie od python 3

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [0]:
np.matmul(A, B)

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

In [0]:
A.dot(B)

array([[ 9,  7],
       [14, 19],
       [37,  4],
       [10, -9]])

Krótkie wprowadzenie do LaTeXa

$$
a^2 + b^2 = c^2
$$


Wzór na średnią arytmetyczną

$$
\bar{x} = \frac{\sum_i^n x_i}{n}
$$

Deklarujemy macierz

$$
A = 
\begin{bmatrix} %pmatrix
1 & 2 \\
3 & 4 
\end{bmatrix}
$$

Zadanie 3. Znajdź macierz transponową $\mathbf{B}^T$

In [0]:
B.T

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [0]:
B.transpose()

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

In [0]:
np.transpose(B)

array([[ 3,  4,  2,  1],
       [ 6,  0, -1,  1]])

Zadanie 4. Znajdź macierz odwrotną $\mathbf{A}^{-1}$

In [0]:
np.linalg.inv(A)

array([[ 1.42207792,  0.2012987 , -0.51298701,  0.63636364],
       [-0.43506494, -0.08441558,  0.34415584, -0.36363636],
       [-0.44805195,  0.03246753,  0.17532468, -0.09090909],
       [-0.66883117,  0.01948052,  0.30519481, -0.45454545]])

In [0]:
np.linalg.inv(A) @ A

array([[ 1.00000000e+00,  4.44089210e-16,  6.66133815e-16,
         0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  1.11022302e-16,
        -2.22044605e-16],
       [-5.55111512e-17, -4.16333634e-17,  1.00000000e+00,
        -5.55111512e-17],
       [ 0.00000000e+00,  2.22044605e-16,  0.00000000e+00,
         1.00000000e+00]])

Zadanie 5. Znajdź macierz $\mathbf{A}^3$

In [0]:
A @ A @ A

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

In [0]:
np.linalg.matrix_power(A, 3)

array([[ -15,   51,   38,  -98],
       [ 190,   94,  111,  261],
       [ 151,  241,  341, -109],
       [ 103,   38,  158,   69]])

## tworzymy tabliczkę mnożenia na kilka sposobów

In [0]:
wynik1 = np.zeros([10,10], dtype = int)
print(wynik1)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [0]:
wynik1[0,0] = 1
print(wynik1)

[[1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [0]:
zakres =  np.arange(0, 10) + 1
print(zakres)

for i in zakres:
  for j in zakres:
    wynik1[i-1, j-1] = i*j

wynik1

[ 1  2  3  4  5  6  7  8  9 10]


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Tabliczka mnożenia macierzowo

In [0]:
Z = np.arange(0,10)+1

Z.reshape(10,1) @ Z.reshape(1, 10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [0]:
np.outer(Z, Z)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Zadanie 6. W programie Python na 3 rózne sposoby zadeklaruj macierz postaci:

In [0]:
dane = np.arange(1, 10)
A = dane.reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1. Wyznacz liczbe wierszy i kolumn macierzy A.
2. Wyznacz sume wszystkich elementów macierzy A.
3. Wyznacz sumy wszytkich elementów w poszczególnych kolumnach macierzy
A.
4. Wyznacz sumy wszytkich elementów w poszczególnych wierszach macierzy A.
5. Wyznacz srednie wszytkich elementów w poszczególnych kolumnach macierzy
A.
6. Wyznacz srednie wszytkich elementów w poszczególnych wierszach macierzy
A.
7. Oblicz A11 + A32.
8. Wyswietl zawartosc drugiej kolumny.
9. Wyswietl zawartosc pierwszego wiersza.

In [0]:
A.shape # zad 6.1
A.sum() # zad 6.2
A.sum(axis = 0) # zad 6.3
A.sum(axis = 1) # zad 6.4
A.mean(axis = 0) # zad 6.5
A.mean(axis = 1) # zad 6.6

A[0,0] + A[2,1] # zad 6.7
A[0][0] + A[2][1] # zad 6.7

A[:, 1] # druga kolumna
A[0, :] # A[0] ## pierwszy wiersz

array([1, 2, 3])